//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class EntitiesOnTour : DbContext
{
    public EntitiesOnTour()
        : base("name=EntitiesOnTour")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<ACTIVIDAD> ACTIVIDADs { get; set; }
    public DbSet<APEX__ACL> APEX__ACL { get; set; }
    public DbSet<APEX__WS_FILES> APEX__WS_FILES { get; set; }
    public DbSet<APEX__WS_LINKS> APEX__WS_LINKS { get; set; }
    public DbSet<APEX__WS_NOTES> APEX__WS_NOTES { get; set; }
    public DbSet<APEX__WS_ROWS> APEX__WS_ROWS { get; set; }
    public DbSet<APEX__WS_TAGS> APEX__WS_TAGS { get; set; }
    public DbSet<APEX__WS_WEBPG_SECTIONS> APEX__WS_WEBPG_SECTIONS { get; set; }
    public DbSet<CLIENTE> CLIENTEs { get; set; }
    public DbSet<CONTRATO> CONTRATOes { get; set; }
    public DbSet<CONTRATO_PAQUETE> CONTRATO_PAQUETE { get; set; }
    public DbSet<CUENTA> CUENTAs { get; set; }
    public DbSet<DEMO_CUSTOMERS> DEMO_CUSTOMERS { get; set; }
    public DbSet<DEMO_ORDER_ITEMS> DEMO_ORDER_ITEMS { get; set; }
    public DbSet<DEMO_ORDERS> DEMO_ORDERS { get; set; }
    public DbSet<DEMO_PRODUCT_INFO> DEMO_PRODUCT_INFO { get; set; }
    public DbSet<DEMO_USERS> DEMO_USERS { get; set; }
    public DbSet<DEPT> DEPTs { get; set; }
    public DbSet<DOCUMENTO> DOCUMENTOes { get; set; }
    public DbSet<EMP> EMPs { get; set; }
    public DbSet<EMPLEADO> EMPLEADOes { get; set; }
    public DbSet<PAQUETEVIAJE> PAQUETEVIAJEs { get; set; }
    public DbSet<SERVICIO> SERVICIOs { get; set; }
    public DbSet<SERVICIO_PAQUETE> SERVICIO_PAQUETE { get; set; }
    public DbSet<TIPO_ACTIVIDAD> TIPO_ACTIVIDAD { get; set; }
    public DbSet<TIPO_SERVICIO> TIPO_SERVICIO { get; set; }
    public DbSet<TIPO_TRANSACCION> TIPO_TRANSACCION { get; set; }
    public DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
    public DbSet<TRANSACCION> TRANSACCIONs { get; set; }
    public DbSet<USUARIO> USUARIOs { get; set; }
    public DbSet<APEX__WS_HISTORY> APEX__WS_HISTORY { get; set; }
    public DbSet<APEX__WS_WEBPG_SECTION_HISTORY> APEX__WS_WEBPG_SECTION_HISTORY { get; set; }
}
