//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;

public partial class EntitiesOnTour : DbContext
{
    public EntitiesOnTour()
        : base("name=EntitiesOnTour")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<ACTIVIDAD> ACTIVIDAD { get; set; }
    public DbSet<CLIENTE> CLIENTE { get; set; }
    public DbSet<CONTRATO> CONTRATO { get; set; }
    public DbSet<CONTRATO_PAQUETE> CONTRATO_PAQUETE { get; set; }
    public DbSet<CUENTA> CUENTA { get; set; }
    public DbSet<DOCUMENTO> DOCUMENTO { get; set; }
    public DbSet<EMPLEADO> EMPLEADO { get; set; }
    public DbSet<PAQUETEVIAJE> PAQUETEVIAJE { get; set; }
    public DbSet<SERVICIO> SERVICIO { get; set; }
    public DbSet<SERVICIO_PAQUETE> SERVICIO_PAQUETE { get; set; }
    public DbSet<TIPO_ACTIVIDAD> TIPO_ACTIVIDAD { get; set; }
    public DbSet<TIPO_SERVICIO> TIPO_SERVICIO { get; set; }
    public DbSet<TIPO_TRANSACCION> TIPO_TRANSACCION { get; set; }
    public DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
    public DbSet<TRANSACCION> TRANSACCION { get; set; }
    public DbSet<USUARIO> USUARIO { get; set; }

    public virtual int SP_INSERTAUSUARIO(string pARAM_LOGIN_USR, string pARAM_PASS_USR, Nullable<decimal> pARAM_ID_TIPO_USUARIO, string pARAM_ACTIVO, ObjectParameter pARA_ID_USR)
    {
        var pARAM_LOGIN_USRParameter = pARAM_LOGIN_USR != null ?
            new ObjectParameter("PARAM_LOGIN_USR", pARAM_LOGIN_USR) :
            new ObjectParameter("PARAM_LOGIN_USR", typeof(string));

        var pARAM_PASS_USRParameter = pARAM_PASS_USR != null ?
            new ObjectParameter("PARAM_PASS_USR", pARAM_PASS_USR) :
            new ObjectParameter("PARAM_PASS_USR", typeof(string));

        var pARAM_ID_TIPO_USUARIOParameter = pARAM_ID_TIPO_USUARIO.HasValue ?
            new ObjectParameter("PARAM_ID_TIPO_USUARIO", pARAM_ID_TIPO_USUARIO) :
            new ObjectParameter("PARAM_ID_TIPO_USUARIO", typeof(decimal));

        var pARAM_ACTIVOParameter = pARAM_ACTIVO != null ?
            new ObjectParameter("PARAM_ACTIVO", pARAM_ACTIVO) :
            new ObjectParameter("PARAM_ACTIVO", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAUSUARIO", pARAM_LOGIN_USRParameter, pARAM_PASS_USRParameter, pARAM_ID_TIPO_USUARIOParameter, pARAM_ACTIVOParameter, pARA_ID_USR);
    }

    public virtual int SP_UPDATECLIENTE(Nullable<decimal> rUT, string nOMBRE, string aPELLIDO_PAT, string aPELLIDO_MAT, string mAIL_CLI, string dIRECCION, Nullable<System.DateTime> fECHA_NACIMIENTO)
    {
        var rUTParameter = rUT.HasValue ?
            new ObjectParameter("RUT", rUT) :
            new ObjectParameter("RUT", typeof(decimal));

        var nOMBREParameter = nOMBRE != null ?
            new ObjectParameter("NOMBRE", nOMBRE) :
            new ObjectParameter("NOMBRE", typeof(string));

        var aPELLIDO_PATParameter = aPELLIDO_PAT != null ?
            new ObjectParameter("APELLIDO_PAT", aPELLIDO_PAT) :
            new ObjectParameter("APELLIDO_PAT", typeof(string));

        var aPELLIDO_MATParameter = aPELLIDO_MAT != null ?
            new ObjectParameter("APELLIDO_MAT", aPELLIDO_MAT) :
            new ObjectParameter("APELLIDO_MAT", typeof(string));

        var mAIL_CLIParameter = mAIL_CLI != null ?
            new ObjectParameter("MAIL_CLI", mAIL_CLI) :
            new ObjectParameter("MAIL_CLI", typeof(string));

        var dIRECCIONParameter = dIRECCION != null ?
            new ObjectParameter("DIRECCION", dIRECCION) :
            new ObjectParameter("DIRECCION", typeof(string));

        var fECHA_NACIMIENTOParameter = fECHA_NACIMIENTO.HasValue ?
            new ObjectParameter("FECHA_NACIMIENTO", fECHA_NACIMIENTO) :
            new ObjectParameter("FECHA_NACIMIENTO", typeof(System.DateTime));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATECLIENTE", rUTParameter, nOMBREParameter, aPELLIDO_PATParameter, aPELLIDO_MATParameter, mAIL_CLIParameter, dIRECCIONParameter, fECHA_NACIMIENTOParameter);
    }
}
