//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ACTIVIDAD
{
    public decimal ID_ACTIVIDAD { get; set; }
    public string DESC_ACTIVIDAD { get; set; }
    public System.DateTime FECHA_REALIZACION_ACT { get; set; }
    public Nullable<decimal> MONTO_RECAUDADO { get; set; }
    public string ACTIVO { get; set; }
    public decimal ID_TIPO_ACTIVIDAD { get; set; }
    public decimal ID_CONTRATO { get; set; }

    public virtual CONTRATO CONTRATO { get; set; }
    public virtual TIPO_ACTIVIDAD TIPO_ACTIVIDAD { get; set; }
}

public partial class APEX__ACL
{
    public decimal ID { get; set; }
    public decimal WS_APP_ID { get; set; }
    public string USERNAME { get; set; }
    public string PRIV { get; set; }
    public System.DateTime CREATED_ON { get; set; }
    public string CREATED_BY { get; set; }
    public Nullable<System.DateTime> UPDATED_ON { get; set; }
    public string UPDATED_BY { get; set; }
}

public partial class APEX__WS_FILES
{
    public decimal ID { get; set; }
    public decimal WS_APP_ID { get; set; }
    public Nullable<decimal> DATA_GRID_ID { get; set; }
    public Nullable<decimal> ROW_ID { get; set; }
    public Nullable<decimal> WEBPAGE_ID { get; set; }
    public string COMPONENT_LEVEL { get; set; }
    public string NAME { get; set; }
    public string IMAGE_ALIAS { get; set; }
    public string IMAGE_ATTRIBUTES { get; set; }
    public byte[] CONTENT { get; set; }
    public Nullable<System.DateTime> CONTENT_LAST_UPDATE { get; set; }
    public string MIME_TYPE { get; set; }
    public string CONTENT_CHARSET { get; set; }
    public string CONTENT_FILENAME { get; set; }
    public string DESCRIPTION { get; set; }
    public System.DateTime CREATED_ON { get; set; }
    public string CREATED_BY { get; set; }
    public Nullable<System.DateTime> UPDATED_ON { get; set; }
    public string UPDATED_BY { get; set; }

    public virtual APEX__WS_ROWS APEX__WS_ROWS { get; set; }
}

public partial class APEX__WS_HISTORY
{
    public decimal ROW_ID { get; set; }
    public decimal WS_APP_ID { get; set; }
    public decimal DATA_GRID_ID { get; set; }
    public string COLUMN_NAME { get; set; }
    public string OLD_VALUE { get; set; }
    public string NEW_VALUE { get; set; }
    public string APPLICATION_USER_ID { get; set; }
    public Nullable<System.DateTime> CHANGE_DATE { get; set; }
}

public partial class APEX__WS_LINKS
{
    public decimal ID { get; set; }
    public decimal WS_APP_ID { get; set; }
    public Nullable<decimal> DATA_GRID_ID { get; set; }
    public Nullable<decimal> ROW_ID { get; set; }
    public Nullable<decimal> WEBPAGE_ID { get; set; }
    public string COMPONENT_LEVEL { get; set; }
    public string TAGS { get; set; }
    public string SHOW_ON_HOMEPAGE { get; set; }
    public string LINK_NAME { get; set; }
    public string URL { get; set; }
    public string LINK_DESCRIPTION { get; set; }
    public Nullable<decimal> DISPLAY_SEQUENCE { get; set; }
    public System.DateTime CREATED_ON { get; set; }
    public string CREATED_BY { get; set; }
    public Nullable<System.DateTime> UPDATED_ON { get; set; }
    public string UPDATED_BY { get; set; }

    public virtual APEX__WS_ROWS APEX__WS_ROWS { get; set; }
}

public partial class APEX__WS_NOTES
{
    public decimal ID { get; set; }
    public decimal WS_APP_ID { get; set; }
    public Nullable<decimal> DATA_GRID_ID { get; set; }
    public Nullable<decimal> ROW_ID { get; set; }
    public Nullable<decimal> WEBPAGE_ID { get; set; }
    public string COMPONENT_LEVEL { get; set; }
    public string CONTENT { get; set; }
    public System.DateTime CREATED_ON { get; set; }
    public string CREATED_BY { get; set; }
    public Nullable<System.DateTime> UPDATED_ON { get; set; }
    public string UPDATED_BY { get; set; }

    public virtual APEX__WS_ROWS APEX__WS_ROWS { get; set; }
}

public partial class APEX__WS_ROWS
{
    public APEX__WS_ROWS()
    {
        this.APEX__WS_FILES = new HashSet<APEX__WS_FILES>();
        this.APEX__WS_LINKS = new HashSet<APEX__WS_LINKS>();
        this.APEX__WS_NOTES = new HashSet<APEX__WS_NOTES>();
        this.APEX__WS_TAGS = new HashSet<APEX__WS_TAGS>();
    }

    public decimal ID { get; set; }
    public decimal WS_APP_ID { get; set; }
    public decimal DATA_GRID_ID { get; set; }
    public string UNIQUE_VALUE { get; set; }
    public string TAGS { get; set; }
    public Nullable<decimal> PARENT_ROW_ID { get; set; }
    public string OWNER { get; set; }
    public string GEOCODE { get; set; }
    public Nullable<decimal> LOAD_ORDER { get; set; }
    public Nullable<decimal> CHANGE_COUNT { get; set; }
    public System.DateTime CREATED_ON { get; set; }
    public string CREATED_BY { get; set; }
    public Nullable<System.DateTime> UPDATED_ON { get; set; }
    public string UPDATED_BY { get; set; }
    public string C001 { get; set; }
    public string C002 { get; set; }
    public string C003 { get; set; }
    public string C004 { get; set; }
    public string C005 { get; set; }
    public string C006 { get; set; }
    public string C007 { get; set; }
    public string C008 { get; set; }
    public string C009 { get; set; }
    public string C010 { get; set; }
    public string C011 { get; set; }
    public string C012 { get; set; }
    public string C013 { get; set; }
    public string C014 { get; set; }
    public string C015 { get; set; }
    public string C016 { get; set; }
    public string C017 { get; set; }
    public string C018 { get; set; }
    public string C019 { get; set; }
    public string C020 { get; set; }
    public string C021 { get; set; }
    public string C022 { get; set; }
    public string C023 { get; set; }
    public string C024 { get; set; }
    public string C025 { get; set; }
    public string C026 { get; set; }
    public string C027 { get; set; }
    public string C028 { get; set; }
    public string C029 { get; set; }
    public string C030 { get; set; }
    public string C031 { get; set; }
    public string C032 { get; set; }
    public string C033 { get; set; }
    public string C034 { get; set; }
    public string C035 { get; set; }
    public string C036 { get; set; }
    public string C037 { get; set; }
    public string C038 { get; set; }
    public string C039 { get; set; }
    public string C040 { get; set; }
    public string C041 { get; set; }
    public string C042 { get; set; }
    public string C043 { get; set; }
    public string C044 { get; set; }
    public string C045 { get; set; }
    public string C046 { get; set; }
    public string C047 { get; set; }
    public string C048 { get; set; }
    public string C049 { get; set; }
    public string C050 { get; set; }
    public Nullable<decimal> N001 { get; set; }
    public Nullable<decimal> N002 { get; set; }
    public Nullable<decimal> N003 { get; set; }
    public Nullable<decimal> N004 { get; set; }
    public Nullable<decimal> N005 { get; set; }
    public Nullable<decimal> N006 { get; set; }
    public Nullable<decimal> N007 { get; set; }
    public Nullable<decimal> N008 { get; set; }
    public Nullable<decimal> N009 { get; set; }
    public Nullable<decimal> N010 { get; set; }
    public Nullable<decimal> N011 { get; set; }
    public Nullable<decimal> N012 { get; set; }
    public Nullable<decimal> N013 { get; set; }
    public Nullable<decimal> N014 { get; set; }
    public Nullable<decimal> N015 { get; set; }
    public Nullable<decimal> N016 { get; set; }
    public Nullable<decimal> N017 { get; set; }
    public Nullable<decimal> N018 { get; set; }
    public Nullable<decimal> N019 { get; set; }
    public Nullable<decimal> N020 { get; set; }
    public Nullable<decimal> N021 { get; set; }
    public Nullable<decimal> N022 { get; set; }
    public Nullable<decimal> N023 { get; set; }
    public Nullable<decimal> N024 { get; set; }
    public Nullable<decimal> N025 { get; set; }
    public Nullable<decimal> N026 { get; set; }
    public Nullable<decimal> N027 { get; set; }
    public Nullable<decimal> N028 { get; set; }
    public Nullable<decimal> N029 { get; set; }
    public Nullable<decimal> N030 { get; set; }
    public Nullable<decimal> N031 { get; set; }
    public Nullable<decimal> N032 { get; set; }
    public Nullable<decimal> N033 { get; set; }
    public Nullable<decimal> N034 { get; set; }
    public Nullable<decimal> N035 { get; set; }
    public Nullable<decimal> N036 { get; set; }
    public Nullable<decimal> N037 { get; set; }
    public Nullable<decimal> N038 { get; set; }
    public Nullable<decimal> N039 { get; set; }
    public Nullable<decimal> N040 { get; set; }
    public Nullable<decimal> N041 { get; set; }
    public Nullable<decimal> N042 { get; set; }
    public Nullable<decimal> N043 { get; set; }
    public Nullable<decimal> N044 { get; set; }
    public Nullable<decimal> N045 { get; set; }
    public Nullable<decimal> N046 { get; set; }
    public Nullable<decimal> N047 { get; set; }
    public Nullable<decimal> N048 { get; set; }
    public Nullable<decimal> N049 { get; set; }
    public Nullable<decimal> N050 { get; set; }
    public Nullable<System.DateTime> D001 { get; set; }
    public Nullable<System.DateTime> D002 { get; set; }
    public Nullable<System.DateTime> D003 { get; set; }
    public Nullable<System.DateTime> D004 { get; set; }
    public Nullable<System.DateTime> D005 { get; set; }
    public Nullable<System.DateTime> D006 { get; set; }
    public Nullable<System.DateTime> D007 { get; set; }
    public Nullable<System.DateTime> D008 { get; set; }
    public Nullable<System.DateTime> D009 { get; set; }
    public Nullable<System.DateTime> D010 { get; set; }
    public Nullable<System.DateTime> D011 { get; set; }
    public Nullable<System.DateTime> D012 { get; set; }
    public Nullable<System.DateTime> D013 { get; set; }
    public Nullable<System.DateTime> D014 { get; set; }
    public Nullable<System.DateTime> D015 { get; set; }
    public Nullable<System.DateTime> D016 { get; set; }
    public Nullable<System.DateTime> D017 { get; set; }
    public Nullable<System.DateTime> D018 { get; set; }
    public Nullable<System.DateTime> D019 { get; set; }
    public Nullable<System.DateTime> D020 { get; set; }
    public Nullable<System.DateTime> D021 { get; set; }
    public Nullable<System.DateTime> D022 { get; set; }
    public Nullable<System.DateTime> D023 { get; set; }
    public Nullable<System.DateTime> D024 { get; set; }
    public Nullable<System.DateTime> D025 { get; set; }
    public Nullable<System.DateTime> D026 { get; set; }
    public Nullable<System.DateTime> D027 { get; set; }
    public Nullable<System.DateTime> D028 { get; set; }
    public Nullable<System.DateTime> D029 { get; set; }
    public Nullable<System.DateTime> D030 { get; set; }
    public Nullable<System.DateTime> D031 { get; set; }
    public Nullable<System.DateTime> D032 { get; set; }
    public Nullable<System.DateTime> D033 { get; set; }
    public Nullable<System.DateTime> D034 { get; set; }
    public Nullable<System.DateTime> D035 { get; set; }
    public Nullable<System.DateTime> D036 { get; set; }
    public Nullable<System.DateTime> D037 { get; set; }
    public Nullable<System.DateTime> D038 { get; set; }
    public Nullable<System.DateTime> D039 { get; set; }
    public Nullable<System.DateTime> D040 { get; set; }
    public Nullable<System.DateTime> D041 { get; set; }
    public Nullable<System.DateTime> D042 { get; set; }
    public Nullable<System.DateTime> D043 { get; set; }
    public Nullable<System.DateTime> D044 { get; set; }
    public Nullable<System.DateTime> D045 { get; set; }
    public Nullable<System.DateTime> D046 { get; set; }
    public Nullable<System.DateTime> D047 { get; set; }
    public Nullable<System.DateTime> D048 { get; set; }
    public Nullable<System.DateTime> D049 { get; set; }
    public Nullable<System.DateTime> D050 { get; set; }
    public string CLOB001 { get; set; }
    public string SEARCH_CLOB { get; set; }

    public virtual ICollection<APEX__WS_FILES> APEX__WS_FILES { get; set; }
    public virtual ICollection<APEX__WS_LINKS> APEX__WS_LINKS { get; set; }
    public virtual ICollection<APEX__WS_NOTES> APEX__WS_NOTES { get; set; }
    public virtual ICollection<APEX__WS_TAGS> APEX__WS_TAGS { get; set; }
}

public partial class APEX__WS_TAGS
{
    public decimal ID { get; set; }
    public decimal WS_APP_ID { get; set; }
    public Nullable<decimal> DATA_GRID_ID { get; set; }
    public Nullable<decimal> ROW_ID { get; set; }
    public Nullable<decimal> WEBPAGE_ID { get; set; }
    public string COMPONENT_LEVEL { get; set; }
    public string TAG { get; set; }
    public System.DateTime CREATED_ON { get; set; }
    public string CREATED_BY { get; set; }
    public Nullable<System.DateTime> UPDATED_ON { get; set; }
    public string UPDATED_BY { get; set; }

    public virtual APEX__WS_ROWS APEX__WS_ROWS { get; set; }
}

public partial class APEX__WS_WEBPG_SECTION_HISTORY
{
    public decimal SECTION_ID { get; set; }
    public decimal WS_APP_ID { get; set; }
    public decimal WEBPAGE_ID { get; set; }
    public Nullable<decimal> OLD_DISPLAY_SEQUENCE { get; set; }
    public Nullable<decimal> NEW_DISPLAY_SEQUENCE { get; set; }
    public string OLD_TITLE { get; set; }
    public string NEW_TITLE { get; set; }
    public string OLD_CONTENT { get; set; }
    public string NEW_CONTENT { get; set; }
    public string APPLICATION_USER_ID { get; set; }
    public System.DateTime CHANGE_DATE { get; set; }
}

public partial class APEX__WS_WEBPG_SECTIONS
{
    public decimal ID { get; set; }
    public decimal WS_APP_ID { get; set; }
    public Nullable<decimal> WEBPAGE_ID { get; set; }
    public Nullable<decimal> DISPLAY_SEQUENCE { get; set; }
    public string SECTION_TYPE { get; set; }
    public string TITLE { get; set; }
    public string CONTENT { get; set; }
    public string CONTENT_UPPER { get; set; }
    public Nullable<decimal> NAV_START_WEBPAGE_ID { get; set; }
    public Nullable<decimal> NAV_MAX_LEVEL { get; set; }
    public string NAV_INCLUDE_LINK { get; set; }
    public Nullable<decimal> DATA_GRID_ID { get; set; }
    public Nullable<decimal> REPORT_ID { get; set; }
    public Nullable<decimal> DATA_SECTION_STYLE { get; set; }
    public string CHART_TYPE { get; set; }
    public string CHART_3D { get; set; }
    public string CHART_LABEL { get; set; }
    public string LABEL_AXIS_TITLE { get; set; }
    public string CHART_VALUE { get; set; }
    public string VALUE_AXIS_TITLE { get; set; }
    public string CHART_AGGREGATE { get; set; }
    public string CHART_SORTING { get; set; }
    public System.DateTime CREATED_ON { get; set; }
    public string CREATED_BY { get; set; }
    public Nullable<System.DateTime> UPDATED_ON { get; set; }
    public string UPDATED_BY { get; set; }
}

public partial class CLIENTE
{
    public CLIENTE()
    {
        this.CONTRATOes = new HashSet<CONTRATO>();
        this.CUENTAs = new HashSet<CUENTA>();
    }

    public decimal NUMRUT_CLI { get; set; }
    public string DRUT_CLI { get; set; }
    public string NOMBRE_CLIE { get; set; }
    public string APELLIDO_PAT_CLI { get; set; }
    public string APELLIDO_MAT_CLI { get; set; }
    public string MAIL_CLI { get; set; }
    public string ACTIVO { get; set; }
    public Nullable<decimal> ID_USR { get; set; }
    public string DIRECCION_CLI { get; set; }
    public Nullable<System.DateTime> FECHA_NACIMIENTO_CLI { get; set; }
    public string FONO_CLI { get; set; }

    public virtual USUARIO USUARIO { get; set; }
    public virtual ICollection<CONTRATO> CONTRATOes { get; set; }
    public virtual ICollection<CUENTA> CUENTAs { get; set; }
}

public partial class CONTRATO
{
    public CONTRATO()
    {
        this.ACTIVIDADs = new HashSet<ACTIVIDAD>();
        this.CONTRATO_PAQUETE = new HashSet<CONTRATO_PAQUETE>();
        this.CUENTAs = new HashSet<CUENTA>();
    }

    public decimal ID_CONTRATO { get; set; }
    public System.DateTime FECHA_INICIO { get; set; }
    public System.DateTime FECHA_TERMINO { get; set; }
    public decimal META { get; set; }
    public Nullable<decimal> MONTO_RESERVA { get; set; }
    public string ESTADO { get; set; }
    public decimal NUMRUT_EMP { get; set; }
    public decimal NUMRUT_CLI_TITULAR { get; set; }

    public virtual ICollection<ACTIVIDAD> ACTIVIDADs { get; set; }
    public virtual CLIENTE CLIENTE { get; set; }
    public virtual EMPLEADO EMPLEADO { get; set; }
    public virtual ICollection<CONTRATO_PAQUETE> CONTRATO_PAQUETE { get; set; }
    public virtual ICollection<CUENTA> CUENTAs { get; set; }
}

public partial class CONTRATO_PAQUETE
{
    public CONTRATO_PAQUETE()
    {
        this.DOCUMENTOes = new HashSet<DOCUMENTO>();
    }

    public decimal ID_CONTRATO { get; set; }
    public decimal ID_PAQUETEVIAJE { get; set; }
    public string ACTIVO { get; set; }

    public virtual CONTRATO CONTRATO { get; set; }
    public virtual PAQUETEVIAJE PAQUETEVIAJE { get; set; }
    public virtual ICollection<DOCUMENTO> DOCUMENTOes { get; set; }
}

public partial class CUENTA
{
    public CUENTA()
    {
        this.TRANSACCIONs = new HashSet<TRANSACCION>();
    }

    public decimal ID_CUENTA { get; set; }
    public decimal SALDO { get; set; }
    public decimal ID_CONTRATO { get; set; }
    public decimal NUMRUT_CLI { get; set; }
    public string ACTIVO { get; set; }

    public virtual CLIENTE CLIENTE { get; set; }
    public virtual CONTRATO CONTRATO { get; set; }
    public virtual ICollection<TRANSACCION> TRANSACCIONs { get; set; }
}

public partial class DEMO_CUSTOMERS
{
    public DEMO_CUSTOMERS()
    {
        this.DEMO_ORDERS = new HashSet<DEMO_ORDERS>();
    }

    public decimal CUSTOMER_ID { get; set; }
    public string CUST_FIRST_NAME { get; set; }
    public string CUST_LAST_NAME { get; set; }
    public string CUST_STREET_ADDRESS1 { get; set; }
    public string CUST_STREET_ADDRESS2 { get; set; }
    public string CUST_CITY { get; set; }
    public string CUST_STATE { get; set; }
    public string CUST_POSTAL_CODE { get; set; }
    public string PHONE_NUMBER1 { get; set; }
    public string PHONE_NUMBER2 { get; set; }
    public Nullable<decimal> CREDIT_LIMIT { get; set; }
    public string CUST_EMAIL { get; set; }

    public virtual ICollection<DEMO_ORDERS> DEMO_ORDERS { get; set; }
}

public partial class DEMO_ORDER_ITEMS
{
    public short ORDER_ITEM_ID { get; set; }
    public decimal ORDER_ID { get; set; }
    public decimal PRODUCT_ID { get; set; }
    public decimal UNIT_PRICE { get; set; }
    public int QUANTITY { get; set; }

    public virtual DEMO_ORDERS DEMO_ORDERS { get; set; }
    public virtual DEMO_PRODUCT_INFO DEMO_PRODUCT_INFO { get; set; }
}

public partial class DEMO_ORDERS
{
    public DEMO_ORDERS()
    {
        this.DEMO_ORDER_ITEMS = new HashSet<DEMO_ORDER_ITEMS>();
    }

    public decimal ORDER_ID { get; set; }
    public decimal CUSTOMER_ID { get; set; }
    public Nullable<decimal> ORDER_TOTAL { get; set; }
    public Nullable<System.DateTime> ORDER_TIMESTAMP { get; set; }
    public Nullable<decimal> USER_ID { get; set; }

    public virtual DEMO_CUSTOMERS DEMO_CUSTOMERS { get; set; }
    public virtual ICollection<DEMO_ORDER_ITEMS> DEMO_ORDER_ITEMS { get; set; }
    public virtual DEMO_USERS DEMO_USERS { get; set; }
}

public partial class DEMO_PRODUCT_INFO
{
    public DEMO_PRODUCT_INFO()
    {
        this.DEMO_ORDER_ITEMS = new HashSet<DEMO_ORDER_ITEMS>();
    }

    public decimal PRODUCT_ID { get; set; }
    public string PRODUCT_NAME { get; set; }
    public string PRODUCT_DESCRIPTION { get; set; }
    public string CATEGORY { get; set; }
    public string PRODUCT_AVAIL { get; set; }
    public Nullable<decimal> LIST_PRICE { get; set; }
    public byte[] PRODUCT_IMAGE { get; set; }
    public string MIMETYPE { get; set; }
    public string FILENAME { get; set; }
    public Nullable<System.DateTime> IMAGE_LAST_UPDATE { get; set; }

    public virtual ICollection<DEMO_ORDER_ITEMS> DEMO_ORDER_ITEMS { get; set; }
}

public partial class DEMO_USERS
{
    public DEMO_USERS()
    {
        this.DEMO_ORDERS = new HashSet<DEMO_ORDERS>();
    }

    public decimal USER_ID { get; set; }
    public string USER_NAME { get; set; }
    public string PASSWORD { get; set; }
    public Nullable<System.DateTime> CREATED_ON { get; set; }
    public Nullable<decimal> QUOTA { get; set; }
    public string PRODUCTS { get; set; }
    public Nullable<System.DateTime> EXPIRES_ON { get; set; }
    public string ADMIN_USER { get; set; }

    public virtual ICollection<DEMO_ORDERS> DEMO_ORDERS { get; set; }
}

public partial class DEPT
{
    public DEPT()
    {
        this.EMPs = new HashSet<EMP>();
    }

    public short DEPTNO { get; set; }
    public string DNAME { get; set; }
    public string LOC { get; set; }

    public virtual ICollection<EMP> EMPs { get; set; }
}

public partial class DOCUMENTO
{
    public decimal ID_DOCUMENTO { get; set; }
    public string URL_DOCUMENTO { get; set; }
    public decimal ID_CONTRATO { get; set; }
    public decimal ID_PAQUETEVIAJE { get; set; }
    public decimal ID_SERVICIO { get; set; }
    public System.DateTime FECHA_SUBIDA_DOC { get; set; }
    public string DESC_DOCUMENTO { get; set; }
    public string ACTIVO { get; set; }

    public virtual CONTRATO_PAQUETE CONTRATO_PAQUETE { get; set; }
    public virtual SERVICIO SERVICIO { get; set; }
}

public partial class EMP
{
    public EMP()
    {
        this.EMP1 = new HashSet<EMP>();
    }

    public short EMPNO { get; set; }
    public string ENAME { get; set; }
    public string JOB { get; set; }
    public Nullable<short> MGR { get; set; }
    public Nullable<System.DateTime> HIREDATE { get; set; }
    public Nullable<decimal> SAL { get; set; }
    public Nullable<decimal> COMM { get; set; }
    public Nullable<short> DEPTNO { get; set; }

    public virtual DEPT DEPT { get; set; }
    public virtual ICollection<EMP> EMP1 { get; set; }
    public virtual EMP EMP2 { get; set; }
}

public partial class EMPLEADO
{
    public EMPLEADO()
    {
        this.CONTRATOes = new HashSet<CONTRATO>();
    }

    public decimal NUMRUT_EMP { get; set; }
    public string DRUT_EMP { get; set; }
    public string NOMBRE_EMP { get; set; }
    public string APELLIDO_PAT_EMP { get; set; }
    public string APELLIDO_MAT_EMP { get; set; }
    public string MAIL_LABORAL { get; set; }
    public string DIRECCION_EMP { get; set; }
    public string ACTIVO { get; set; }
    public decimal ID_USR { get; set; }
    public Nullable<System.DateTime> FECHA_NACIMIENTO_EMP { get; set; }
    public string FONO_EMP { get; set; }

    public virtual ICollection<CONTRATO> CONTRATOes { get; set; }
    public virtual USUARIO USUARIO { get; set; }
}

public partial class PAQUETEVIAJE
{
    public PAQUETEVIAJE()
    {
        this.CONTRATO_PAQUETE = new HashSet<CONTRATO_PAQUETE>();
        this.SERVICIO_PAQUETE = new HashSet<SERVICIO_PAQUETE>();
    }

    public decimal ID_PAQUETEVIAJE { get; set; }
    public string DESC_PAQUETEVIAJE { get; set; }
    public decimal VALOR_PAQUETEVIAJE { get; set; }
    public string ACTIVO { get; set; }
    public System.DateTime FECHA_CREACION_PAQVIAJE { get; set; }

    public virtual ICollection<CONTRATO_PAQUETE> CONTRATO_PAQUETE { get; set; }
    public virtual ICollection<SERVICIO_PAQUETE> SERVICIO_PAQUETE { get; set; }
}

public partial class SERVICIO
{
    public SERVICIO()
    {
        this.DOCUMENTOes = new HashSet<DOCUMENTO>();
        this.SERVICIO_PAQUETE = new HashSet<SERVICIO_PAQUETE>();
    }

    public decimal ID_SERVICIO { get; set; }
    public decimal ID_SERVICIO_WS { get; set; }
    public string ACTIVO { get; set; }
    public decimal ID_TIPO_SERVICIO { get; set; }

    public virtual ICollection<DOCUMENTO> DOCUMENTOes { get; set; }
    public virtual ICollection<SERVICIO_PAQUETE> SERVICIO_PAQUETE { get; set; }
    public virtual TIPO_SERVICIO TIPO_SERVICIO { get; set; }
}

public partial class SERVICIO_PAQUETE
{
    public decimal ID_SERVICIO { get; set; }
    public decimal ID_PAQUETEVIAJE { get; set; }
    public string ACTIVO { get; set; }

    public virtual PAQUETEVIAJE PAQUETEVIAJE { get; set; }
    public virtual SERVICIO SERVICIO { get; set; }
}

public partial class TIPO_ACTIVIDAD
{
    public TIPO_ACTIVIDAD()
    {
        this.ACTIVIDADs = new HashSet<ACTIVIDAD>();
    }

    public decimal ID_TIPO_ACTIIVIDAD { get; set; }
    public string DESC_TIPO_ACT { get; set; }

    public virtual ICollection<ACTIVIDAD> ACTIVIDADs { get; set; }
}

public partial class TIPO_SERVICIO
{
    public TIPO_SERVICIO()
    {
        this.SERVICIOs = new HashSet<SERVICIO>();
    }

    public decimal ID_TIPO_SERVICIO { get; set; }
    public string DESC_SERVICIO { get; set; }

    public virtual ICollection<SERVICIO> SERVICIOs { get; set; }
}

public partial class TIPO_TRANSACCION
{
    public TIPO_TRANSACCION()
    {
        this.TRANSACCIONs = new HashSet<TRANSACCION>();
    }

    public decimal ID_TIPO_TRANSACCION { get; set; }
    public string DESC_TRANSACCION { get; set; }

    public virtual ICollection<TRANSACCION> TRANSACCIONs { get; set; }
}

public partial class TIPO_USUARIO
{
    public TIPO_USUARIO()
    {
        this.USUARIOs = new HashSet<USUARIO>();
    }

    public decimal ID_TIPO_USUARIO { get; set; }
    public string DESC_TIPO_USUARIO { get; set; }

    public virtual ICollection<USUARIO> USUARIOs { get; set; }
}

public partial class TRANSACCION
{
    public decimal ID_TRANSACCION { get; set; }
    public System.DateTime FECHA_TRANSACCION { get; set; }
    public decimal MONTO_TRANSACCION { get; set; }
    public decimal ID_CUENTA { get; set; }
    public decimal ID_TIPO_TRANSACCION { get; set; }
    public string ACTIVO { get; set; }

    public virtual CUENTA CUENTA { get; set; }
    public virtual TIPO_TRANSACCION TIPO_TRANSACCION { get; set; }
}

public partial class USUARIO
{
    public USUARIO()
    {
        this.CLIENTEs = new HashSet<CLIENTE>();
        this.EMPLEADOes = new HashSet<EMPLEADO>();
    }

    public decimal ID_USR { get; set; }
    public string LOGIN_USR { get; set; }
    public string PASS_USR { get; set; }
    public decimal ID_TIPO_USUARIO { get; set; }
    public string ACTIVO { get; set; }

    public virtual ICollection<CLIENTE> CLIENTEs { get; set; }
    public virtual ICollection<EMPLEADO> EMPLEADOes { get; set; }
    public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
}
