//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ACTIVIDAD
{
    public decimal ID_ACTIVIDAD { get; set; }
    public string DESC_ACTIVIDAD { get; set; }
    public System.DateTime FECHA_REALIZACION_ACT { get; set; }
    public Nullable<decimal> MONTO_RECAUDADO { get; set; }
    public string ACTIVO { get; set; }
    public decimal ID_TIPO_ACTIVIDAD { get; set; }
    public decimal ID_CONTRATO { get; set; }

    public virtual CONTRATO CONTRATO { get; set; }
    public virtual TIPO_ACTIVIDAD TIPO_ACTIVIDAD { get; set; }
}

public partial class CLIENTE
{
    public CLIENTE()
    {
        this.CONTRATO = new HashSet<CONTRATO>();
        this.CUENTA = new HashSet<CUENTA>();
    }

    public decimal NUMRUT_CLI { get; set; }
    public string DRUT_CLI { get; set; }
    public string NOMBRE_CLIE { get; set; }
    public string APELLIDO_PAT_CLI { get; set; }
    public string APELLIDO_MAT_CLI { get; set; }
    public string MAIL_CLI { get; set; }
    public string ACTIVO { get; set; }
    public Nullable<decimal> ID_USR { get; set; }
    public string DIRECCION_CLI { get; set; }
    public Nullable<System.DateTime> FECHA_NACIMIENTO_CLI { get; set; }
    public string FONO_CLI { get; set; }

    public virtual USUARIO USUARIO { get; set; }
    public virtual ICollection<CONTRATO> CONTRATO { get; set; }
    public virtual ICollection<CUENTA> CUENTA { get; set; }
}

public partial class CONTRATO
{
    public CONTRATO()
    {
        this.ACTIVIDAD = new HashSet<ACTIVIDAD>();
        this.CONTRATO_PAQUETE = new HashSet<CONTRATO_PAQUETE>();
        this.CUENTA = new HashSet<CUENTA>();
    }

    public decimal ID_CONTRATO { get; set; }
    public System.DateTime FECHA_INICIO { get; set; }
    public System.DateTime FECHA_TERMINO { get; set; }
    public decimal META { get; set; }
    public Nullable<decimal> MONTO_RESERVA { get; set; }
    public string ESTADO { get; set; }
    public decimal NUMRUT_EMP { get; set; }
    public decimal NUMRUT_CLI_TITULAR { get; set; }

    public virtual ICollection<ACTIVIDAD> ACTIVIDAD { get; set; }
    public virtual CLIENTE CLIENTE { get; set; }
    public virtual EMPLEADO EMPLEADO { get; set; }
    public virtual ICollection<CONTRATO_PAQUETE> CONTRATO_PAQUETE { get; set; }
    public virtual ICollection<CUENTA> CUENTA { get; set; }
}

public partial class CONTRATO_PAQUETE
{
    public CONTRATO_PAQUETE()
    {
        this.DOCUMENTO = new HashSet<DOCUMENTO>();
    }

    public decimal ID_CONTRATO { get; set; }
    public decimal ID_PAQUETEVIAJE { get; set; }
    public string ACTIVO { get; set; }

    public virtual CONTRATO CONTRATO { get; set; }
    public virtual PAQUETEVIAJE PAQUETEVIAJE { get; set; }
    public virtual ICollection<DOCUMENTO> DOCUMENTO { get; set; }
}

public partial class CUENTA
{
    public CUENTA()
    {
        this.TRANSACCION = new HashSet<TRANSACCION>();
    }

    public decimal ID_CUENTA { get; set; }
    public decimal SALDO { get; set; }
    public decimal ID_CONTRATO { get; set; }
    public decimal NUMRUT_CLI { get; set; }
    public string ACTIVO { get; set; }

    public virtual CLIENTE CLIENTE { get; set; }
    public virtual CONTRATO CONTRATO { get; set; }
    public virtual ICollection<TRANSACCION> TRANSACCION { get; set; }
}

public partial class DOCUMENTO
{
    public decimal ID_DOCUMENTO { get; set; }
    public string URL_DOCUMENTO { get; set; }
    public decimal ID_CONTRATO { get; set; }
    public decimal ID_PAQUETEVIAJE { get; set; }
    public decimal ID_SERVICIO { get; set; }
    public System.DateTime FECHA_SUBIDA_DOC { get; set; }
    public string DESC_DOCUMENTO { get; set; }
    public string ACTIVO { get; set; }

    public virtual CONTRATO_PAQUETE CONTRATO_PAQUETE { get; set; }
    public virtual SERVICIO SERVICIO { get; set; }
}

public partial class EMPLEADO
{
    public EMPLEADO()
    {
        this.CONTRATO = new HashSet<CONTRATO>();
    }

    public decimal NUMRUT_EMP { get; set; }
    public string DRUT_EMP { get; set; }
    public string NOMBRE_EMP { get; set; }
    public string APELLIDO_PAT_EMP { get; set; }
    public string APELLIDO_MAT_EMP { get; set; }
    public string MAIL_LABORAL { get; set; }
    public string DIRECCION_EMP { get; set; }
    public string ACTIVO { get; set; }
    public decimal ID_USR { get; set; }
    public Nullable<System.DateTime> FECHA_NACIMIENTO_EMP { get; set; }
    public string FONO_EMP { get; set; }

    public virtual ICollection<CONTRATO> CONTRATO { get; set; }
    public virtual USUARIO USUARIO { get; set; }
}

public partial class PAQUETEVIAJE
{
    public PAQUETEVIAJE()
    {
        this.CONTRATO_PAQUETE = new HashSet<CONTRATO_PAQUETE>();
        this.SERVICIO_PAQUETE = new HashSet<SERVICIO_PAQUETE>();
    }

    public decimal ID_PAQUETEVIAJE { get; set; }
    public string DESC_PAQUETEVIAJE { get; set; }
    public decimal VALOR_PAQUETEVIAJE { get; set; }
    public string ACTIVO { get; set; }
    public System.DateTime FECHA_CREACION_PAQVIAJE { get; set; }

    public virtual ICollection<CONTRATO_PAQUETE> CONTRATO_PAQUETE { get; set; }
    public virtual ICollection<SERVICIO_PAQUETE> SERVICIO_PAQUETE { get; set; }
}

public partial class SERVICIO
{
    public SERVICIO()
    {
        this.DOCUMENTO = new HashSet<DOCUMENTO>();
        this.SERVICIO_PAQUETE = new HashSet<SERVICIO_PAQUETE>();
    }

    public decimal ID_SERVICIO { get; set; }
    public decimal ID_SERVICIO_WS { get; set; }
    public string ACTIVO { get; set; }
    public decimal ID_TIPO_SERVICIO { get; set; }

    public virtual ICollection<DOCUMENTO> DOCUMENTO { get; set; }
    public virtual ICollection<SERVICIO_PAQUETE> SERVICIO_PAQUETE { get; set; }
    public virtual TIPO_SERVICIO TIPO_SERVICIO { get; set; }
}

public partial class SERVICIO_PAQUETE
{
    public decimal ID_SERVICIO { get; set; }
    public decimal ID_PAQUETEVIAJE { get; set; }
    public string ACTIVO { get; set; }

    public virtual PAQUETEVIAJE PAQUETEVIAJE { get; set; }
    public virtual SERVICIO SERVICIO { get; set; }
}

public partial class TIPO_ACTIVIDAD
{
    public TIPO_ACTIVIDAD()
    {
        this.ACTIVIDAD = new HashSet<ACTIVIDAD>();
    }

    public decimal ID_TIPO_ACTIIVIDAD { get; set; }
    public string DESC_TIPO_ACT { get; set; }

    public virtual ICollection<ACTIVIDAD> ACTIVIDAD { get; set; }
}

public partial class TIPO_SERVICIO
{
    public TIPO_SERVICIO()
    {
        this.SERVICIO = new HashSet<SERVICIO>();
    }

    public decimal ID_TIPO_SERVICIO { get; set; }
    public string DESC_SERVICIO { get; set; }

    public virtual ICollection<SERVICIO> SERVICIO { get; set; }
}

public partial class TIPO_TRANSACCION
{
    public TIPO_TRANSACCION()
    {
        this.TRANSACCION = new HashSet<TRANSACCION>();
    }

    public decimal ID_TIPO_TRANSACCION { get; set; }
    public string DESC_TRANSACCION { get; set; }

    public virtual ICollection<TRANSACCION> TRANSACCION { get; set; }
}

public partial class TIPO_USUARIO
{
    public TIPO_USUARIO()
    {
        this.USUARIO = new HashSet<USUARIO>();
    }

    public decimal ID_TIPO_USUARIO { get; set; }
    public string DESC_TIPO_USUARIO { get; set; }

    public virtual ICollection<USUARIO> USUARIO { get; set; }
}

public partial class TRANSACCION
{
    public decimal ID_TRANSACCION { get; set; }
    public System.DateTime FECHA_TRANSACCION { get; set; }
    public decimal MONTO_TRANSACCION { get; set; }
    public decimal ID_CUENTA { get; set; }
    public decimal ID_TIPO_TRANSACCION { get; set; }
    public string ACTIVO { get; set; }

    public virtual CUENTA CUENTA { get; set; }
    public virtual TIPO_TRANSACCION TIPO_TRANSACCION { get; set; }
}

public partial class USUARIO
{
    public USUARIO()
    {
        this.CLIENTE = new HashSet<CLIENTE>();
        this.EMPLEADO = new HashSet<EMPLEADO>();
    }

    public decimal ID_USR { get; set; }
    public string LOGIN_USR { get; set; }
    public string PASS_USR { get; set; }
    public decimal ID_TIPO_USUARIO { get; set; }
    public string ACTIVO { get; set; }

    public virtual ICollection<CLIENTE> CLIENTE { get; set; }
    public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
    public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
}
